title: HMT Red Teaming
description: HMT Red Teaming
theme: minima

plugins:
  - jekyll-scholar

scholar:
  style: apa
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"